const products: Product[] = [
  {
    image: 'nike-airmax.jpg',
    title: 'Nike Air Max 270',
    description: 'Breathable mesh upper with a lightweight, durable rubber sole for everyday wear.',
    category: 'footwear',
    brand: 'nike',
    price: 150,
    salePrice: 120,
    totalStock: 50,
    averageReview: 4.5,
  },
  {
    image: 'adidas-tee.jpg',
    title: 'Adidas Performance T-Shirt',
    description: 'A quick-dry t-shirt designed for all kinds of sports and workouts.',
    category: 'men',
    brand: 'adidas',
    price: 40,
    salePrice: 35,
    totalStock: 200,
    averageReview: 4.3,
  },
  {
    image: 'puma-shoes.jpg',
    title: 'Puma Running Shoes',
    description: 'Lightweight running shoes with superior grip for daily jogging and intense running.',
    category: 'footwear',
    brand: 'puma',
    price: 100,
    salePrice: 90,
    totalStock: 75,
    averageReview: 4.6,
  },
  {
    image: 'levi-jeans.jpg',
    title: "Levi's 501 Original Jeans",
    description: 'Classic straight-fit jeans made with durable denim for long-lasting comfort.',
    category: 'men',
    brand: 'levi',
    price: 90,
    salePrice: 85,
    totalStock: 120,
    averageReview: 4.8,
  },
  {
    image: 'zara-dress.jpg',
    title: 'Zara Summer Dress',
    description: 'A chic and elegant summer dress made with lightweight, breathable fabric.',
    category: 'women',
    brand: 'zara',
    price: 70,
    salePrice: 60,
    totalStock: 45,
    averageReview: 4.2,
  },
  {
    image: 'hm-coat.jpg',
    title: 'H&M Trench Coat',
    description: 'A stylish, waterproof trench coat perfect for the rainy season.',
    category: 'women',
    brand: 'h&m',
    price: 120,
    salePrice: 100,
    totalStock: 80,
    averageReview: 4.7,
  },
  {
    image: 'baby-jacket.jpg',
    title: 'Baby Hooded Jacket',
    description: 'Soft and cozy hooded jacket to keep your little ones warm during the cold season.',
    category: 'kids',
    brand: 'nike',
    price: 55,
    salePrice: 50,
    totalStock: 30,
    averageReview: 4.4,
  },
  {
    image: 'watch.jpg',
    title: 'Classic Leather Watch',
    description: 'Timeless leather wristwatch with a stainless-steel frame for a sleek look.',
    category: 'accessories',
    brand: 'zara',
    price: 150,
    salePrice: 140,
    totalStock: 20,
    averageReview: 4.9,
  },
  {
    image: 'sneakers.jpg',
    title: 'Adidas Sneakers',
    description: 'Comfortable sneakers with a modern look, perfect for casual outings.',
    category: 'footwear',
    brand: 'adidas',
    price: 110,
    salePrice: 100,
    totalStock: 60,
    averageReview: 4.5,
  },
  {
    image: 'cap.jpg',
    title: 'Puma Sports Cap',
    description: 'Lightweight cap designed to keep you cool while exercising outdoors.',
    category: 'accessories',
    brand: 'puma',
    price: 25,
    salePrice: 20,
    totalStock: 100,
    averageReview: 4.3,
  },
  {
    image: 'levi-jacket.jpg',
    title: "Levi's Denim Jacket",
    description: 'Classic denim jacket that adds rugged style to your casual outfits.',
    category: 'men',
    brand: 'levi',
    price: 110,
    salePrice: 100,
    totalStock: 70,
    averageReview: 4.6,
  },
  {
    image: 'zara-blazer.jpg',
    title: 'Zara Linen Blazer',
    description: 'Lightweight, breathable linen blazer perfect for semi-formal occasions.',
    category: 'women',
    brand: 'zara',
    price: 130,
    salePrice: 120,
    totalStock: 50,
    averageReview: 4.5,
  },
  {
    image: 'h&m-scarf.jpg',
    title: 'H&M Wool Scarf',
    description: 'Soft wool scarf to keep you warm in style during the winter season.',
    category: 'accessories',
    brand: 'h&m',
    price: 30,
    salePrice: 25,
    totalStock: 150,
    averageReview: 4.4,
  },
  {
    image: 'nike-joggers.jpg',
    title: 'Nike Sports Joggers',
    description: 'Comfortable joggers made with moisture-wicking fabric for workouts and casual wear.',
    category: 'men',
    brand: 'nike',
    price: 60,
    salePrice: 55,
    totalStock: 90,
    averageReview: 4.7,
  },
  {
    image: 'adidas-hoodie.jpg',
    title: 'Adidas Essentials Hoodie',
    description: 'Cozy fleece hoodie for a relaxed, comfortable fit.',
    category: 'men',
    brand: 'adidas',
    price: 65,
    salePrice: 60,
    totalStock: 130,
    averageReview: 4.8,
  },
  {
    image: 'puma-backpack.jpg',
    title: 'Puma Sports Backpack',
    description: 'Spacious backpack with multiple compartments for carrying all your essentials.',
    category: 'accessories',
    brand: 'puma',
    price: 70,
    salePrice: 65,
    totalStock: 80,
    averageReview: 4.5,
  },
  {
    image: 'kids-shoes.jpg',
    title: 'Adidas Kids Sneakers',
    description: 'Durable sneakers designed for kids, providing comfort and flexibility.',
    category: 'kids',
    brand: 'adidas',
    price: 45,
    salePrice: 40,
    totalStock: 100,
    averageReview: 4.6,
  },
  {
    image: 'hm-sunglasses.jpg',
    title: 'H&M Sunglasses',
    description: 'Stylish polarized sunglasses offering UV protection and a sleek design.',
    category: 'accessories',
    brand: 'h&m',
    price: 40,
    salePrice: 35,
    totalStock: 110,
    averageReview: 4.3,
  },
  {
    image: 'baby-shoes.jpg',
    title: 'Nike Baby Sneakers',
    description: 'Soft, flexible sneakers for infants to support their first steps.',
    category: 'kids',
    brand: 'nike',
    price: 35,
    salePrice: 30,
    totalStock: 60,
    averageReview: 4.7,
  },
  {
    image: 'zara-tote.jpg',
    title: 'Zara Leather Tote Bag',
    description: 'Elegant leather tote bag, ideal for daily use with ample storage space.',
    category: 'accessories',
    brand: 'zara',
    price: 180,
    salePrice: 160,
    totalStock: 25,
    averageReview: 4.9,
  },
  {
    image: 'levi-shorts.jpg',
    title: "Levi's Cargo Shorts",
    description: 'Comfortable and durable cargo shorts, perfect for casual summer outings.',
    category: 'men',
    brand: 'levi',
    price: 50,
    salePrice: 45,
    totalStock: 150,
    averageReview: 4.5,
  },
  {
    image: 'baby-onesie.jpg',
    title: 'Adidas Baby Onesie',
    description: 'Soft and breathable onesie for infants, perfect for all-day comfort.',
    category: 'kids',
    brand: 'adidas',
    price: 20,
    salePrice: 18,
    totalStock: 80,
    averageReview: 4.8,
  },
  {
    image: 'hm-handbag.jpg',
    title: 'H&M Crossbody Handbag',
    description: 'Compact yet spacious handbag with an adjustable strap for a chic look.',
    category: 'accessories',
    brand: 'h&m',
    price: 50,
    salePrice: 45,
    totalStock: 60,
    averageReview: 4.6,
  },
  {
    image: 'puma-tshirt.jpg',
    title: 'Puma Graphic T-Shirt',
    description: 'Soft cotton t-shirt with a bold graphic print for everyday wear.',
    category: 'men',
    brand: 'puma',
    price: 30,
    salePrice: 25,
    totalStock: 200,
    averageReview: 4.2,
  },
  {
    image: 'zara-blouse.jpg',
    title: 'Zara Floral Blouse',
    description: 'Lightweight blouse with a floral print, perfect for summer.',
    category: 'women',
    brand: 'zara',
    price: 60,
    salePrice: 50,
    totalStock: 70,
    averageReview: 4.4,
  },
];
